OreburghCity_Flat3_F2_MapScripts::
	.byte 0

OreburghCity_Flat3_F2_EventScript_PtNpc1::
	msgbox OreburghCity_Flat3_F2_Text_PtNpc1, MSGBOX_NPC
	end

OreburghCity_Flat3_F2_Text_PtNpc1:
	.string "I'm going to be a GYM LEADER just\n"
	.string "like ROARK!$"

OreburghCity_Flat3_F2_EventScript_PtNpc2::
	msgbox OreburghCity_Flat3_F2_Text_PtNpc2, MSGBOX_NPC
	end

OreburghCity_Flat3_F2_Text_PtNpc2:
	.string "In my youth, I too dug coal in\n"
	.string "that mine.$"

OreburghCity_Flat3_F2_EventScript_PtNpc3::
	msgbox OreburghCity_Flat3_F2_Text_PtNpc3, MSGBOX_NPC
	end

OreburghCity_Flat3_F2_Text_PtNpc3:
	.string "I study fossils. Some can be\n"
	.string "brought back to life as POKéMON!$"
