JubilifeCity_PoketchCompany_F3_MapScripts::
	.byte 0

JubilifeCity_PoketchCompany_F3_EventScript_President::
	msgbox JubilifeCity_PoketchCompany_F3_Text_President, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F3_Text_President:
	.string "I founded this company to help\n"
	.string "Trainers on their journeys.\p"
	.string "One day every Trainer in Sinnoh\n"
	.string "will wear one of our watches!$"

