JubilifeCity_PoketchCompany_F3_MapScripts::
	.byte 0

JubilifeCity_PoketchCompany_F3_EventScript_PtNpc1::
	msgbox JubilifeCity_PoketchCompany_F3_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F3_Text_PtNpc1:
	.string "I'm testing the step counter app.\n"
	.string "I've walked all day!$"

JubilifeCity_PoketchCompany_F3_EventScript_PtNpc2::
	msgbox JubilifeCity_PoketchCompany_F3_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F3_Text_PtNpc2:
	.string "The president works on this floor.\n"
	.string "He's very busy.$"

JubilifeCity_PoketchCompany_F3_EventScript_PtNpc3::
	msgbox JubilifeCity_PoketchCompany_F3_Text_PtNpc3, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F3_Text_PtNpc3:
	.string "A good POKéTCH app should be\n"
	.string "simple and useful.$"
