SandgemTown_RivalHouse_F1_MapScripts::
	.byte 0

SandgemTown_RivalHouse_F1_EventScript_PtNpc1::
	msgbox SandgemTown_RivalHouse_F1_Text_PtNpc1, MSGBOX_NPC
	end

SandgemTown_RivalHouse_F1_Text_PtNpc1:
	.string "My kid works with PROFESSOR ROWAN.\n"
	.string "I couldn't be prouder.$"

SandgemTown_RivalHouse_F1_EventScript_PtNpc2::
	msgbox SandgemTown_RivalHouse_F1_Text_PtNpc2, MSGBOX_NPC
	end

SandgemTown_RivalHouse_F1_Text_PtNpc2:
	.string "I'm going to be a POKéMON\n"
	.string "researcher when I grow up, just\l"
	.string "like my big sibling!$"
