TwinleafTown_Haouse1_MapScripts::
	.byte 0

TwinleafTown_Haouse1_EventScript_PtNpc1::
	msgbox TwinleafTown_Haouse1_Text_PtNpc1, MSGBOX_NPC
	end

TwinleafTown_Haouse1_Text_PtNpc1:
	.string "When I was young, I traveled all\n"
	.string "of Sinnoh with my POKéMON. Those\l"
	.string "were good days.$"

TwinleafTown_Haouse1_EventScript_PtNpc2::
	msgbox TwinleafTown_Haouse1_Text_PtNpc2, MSGBOX_NPC
	end

TwinleafTown_Haouse1_Text_PtNpc2:
	.string "I'm going to go on an adventure\n"
	.string "too! As soon as I'm a bit taller!$"
