TwinleafTown_Haouse1_MapScripts::
	.byte 0

TwinleafTown_Haouse1_EventScript_Woman::
	msgbox TwinleafTown_Haouse1_Text_Woman, MSGBOX_NPC
	end

TwinleafTown_Haouse1_EventScript_Boy::
	msgbox TwinleafTown_Haouse1_Text_Boy, MSGBOX_NPC
	end

TwinleafTown_Haouse1_Text_Woman:
	.string "My son dreams of becoming a\n"
	.string "Trainer. He keeps asking when\l"
	.string "he'll be old enough!$"

TwinleafTown_Haouse1_Text_Boy:
	.string "When I grow up, I'm going to\n"
	.string "battle at the POKéMON LEAGUE! Just\l"
	.string "you wait!$"

