JubilifeCity_PoketchCompany_F1_MapScripts::
	.byte 0

JubilifeCity_PoketchCompany_F1_EventScript_PtNpc1::
	msgbox JubilifeCity_PoketchCompany_F1_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_Text_PtNpc1:
	.string "We build and test new POKéTCH apps\n"
	.string "here every day.$"

JubilifeCity_PoketchCompany_F1_EventScript_PtNpc2::
	msgbox JubilifeCity_PoketchCompany_F1_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_Text_PtNpc2:
	.string "Welcome to the POKéTCH COMPANY!\n"
	.string "Our president is upstairs.$"

JubilifeCity_PoketchCompany_F1_EventScript_PtNpc3::
	msgbox JubilifeCity_PoketchCompany_F1_Text_PtNpc3, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F1_Text_PtNpc3:
	.string "I want a POKéTCH so badly. They\n"
	.string "say there's a campaign in town!$"
