EternaCity_House1_MapScripts::
	.byte 0

EternaCity_House1_EventScript_PtNpc1::
	msgbox EternaCity_House1_Text_PtNpc1, MSGBOX_NPC
	end

EternaCity_House1_Text_PtNpc1:
	.string "Our family has lived in ETERNA for\n"
	.string "generations.$"

EternaCity_House1_EventScript_PtNpc2::
	msgbox EternaCity_House1_Text_PtNpc2, MSGBOX_NPC
	end

EternaCity_House1_Text_PtNpc2:
	.string "The statue was here before the\n"
	.string "city itself was built.$"

EternaCity_House1_EventScript_PtNpc3::
	msgbox EternaCity_House1_Text_PtNpc3, MSGBOX_NPC
	end

EternaCity_House1_Text_PtNpc3:
	.string "I breed POKéMON. Taking care of\n"
	.string "them is my joy.$"
