OreburghCity_Flat2_F1_MapScripts::
	.byte 0

OreburghCity_Flat2_F1_EventScript_PtNpc1::
	msgbox OreburghCity_Flat2_F1_Text_PtNpc1, MSGBOX_NPC
	end

OreburghCity_Flat2_F1_Text_PtNpc1:
	.string "OREBURGH was built by miners over\n"
	.string "a hundred years ago.$"

OreburghCity_Flat2_F1_EventScript_PtNpc2::
	msgbox OreburghCity_Flat2_F1_Text_PtNpc2, MSGBOX_NPC
	end

OreburghCity_Flat2_F1_Text_PtNpc2:
	.string "ROARK visits the mine every\n"
	.string "morning before opening the GYM.$"

OreburghCity_Flat2_F1_EventScript_PtNpc3::
	msgbox OreburghCity_Flat2_F1_Text_PtNpc3, MSGBOX_NPC
	end

OreburghCity_Flat2_F1_Text_PtNpc3:
	.string "Rock-type POKéMON love this town.$"
