FloaromaTown_House1_MapScripts::
	.byte 0

FloaromaTown_House1_EventScript_PtNpc1::
	msgbox FloaromaTown_House1_Text_PtNpc1, MSGBOX_NPC
	end

FloaromaTown_House1_Text_PtNpc1:
	.string "My daughter loves flowers. She\n"
	.string "wants to open her own shop\l"
	.string "someday.$"

FloaromaTown_House1_EventScript_PtNpc2::
	msgbox FloaromaTown_House1_Text_PtNpc2, MSGBOX_NPC
	end

FloaromaTown_House1_Text_PtNpc2:
	.string "I'm going to plant a whole field\n"
	.string "of flowers when I grow up!$"

FloaromaTown_House1_EventScript_PtNpc3::
	msgbox FloaromaTown_House1_Text_PtNpc3, MSGBOX_NPC
	end

FloaromaTown_House1_Text_PtNpc3:
	.string "Clefairy! Fairy!$"
