FloaromaMeadow_House_MapScripts::
	.byte 0

FloaromaMeadow_House_EventScript_PtNpc1::
	msgbox FloaromaMeadow_House_Text_PtNpc1, MSGBOX_NPC
	end

FloaromaMeadow_House_Text_PtNpc1:
	.string "I sell the HONEY from this meadow.\n"
	.string "It's the best in all of Sinnoh!$"

FloaromaMeadow_House_EventScript_PtNpc2::
	msgbox FloaromaMeadow_House_Text_PtNpc2, MSGBOX_NPC
	end

FloaromaMeadow_House_Text_PtNpc2:
	.string "The HONEY man is my hero! One day\n"
	.string "I'll collect HONEY too!$"
