JubilifeCity_Flat2_F1_MapScripts::
	.byte 0

JubilifeCity_Flat2_F1_EventScript_PtNpc1::
	msgbox JubilifeCity_Flat2_F1_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_Flat2_F1_Text_PtNpc1:
	.string "I train every morning in the park\n"
	.string "before work.$"

JubilifeCity_Flat2_F1_EventScript_PtNpc2::
	msgbox JubilifeCity_Flat2_F1_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_Flat2_F1_Text_PtNpc2:
	.string "My PACHIRISU is so cute. It stores\n"
	.string "berries in its cheeks!$"

JubilifeCity_Flat2_F1_EventScript_PtNpc3::
	msgbox JubilifeCity_Flat2_F1_Text_PtNpc3, MSGBOX_NPC
	end

JubilifeCity_Flat2_F1_Text_PtNpc3:
	.string "Pachi!$"
