SandgemTown_House1_MapScripts::
	.byte 0

SandgemTown_House1_EventScript_PtNpc1::
	msgbox SandgemTown_House1_Text_PtNpc1, MSGBOX_NPC
	end

SandgemTown_House1_Text_PtNpc1:
	.string "My wife and I love watching the\n"
	.string "waves from our window.$"

SandgemTown_House1_EventScript_PtNpc2::
	msgbox SandgemTown_House1_Text_PtNpc2, MSGBOX_NPC
	end

SandgemTown_House1_Text_PtNpc2:
	.string "Did you know? Some POKéMON only\n"
	.string "appear near water.$"
