SandgemTown_House1_MapScripts::
	.byte 0

SandgemTown_House1_EventScript_Man::
	msgbox SandgemTown_House1_Text_Man, MSGBOX_NPC
	end

SandgemTown_House1_EventScript_Girl::
	msgbox SandgemTown_House1_Text_Girl, MSGBOX_NPC
	end

SandgemTown_House1_Text_Man:
	.string "PROFESSOR ROWAN came back from\n"
	.string "KANTO recently. Sandgem got a lot\l"
	.string "livelier!$"

SandgemTown_House1_Text_Girl:
	.string "I want to be a POKéMON researcher,\n"
	.string "just like the Professor's\l"
	.string "assistant!$"

