FloaromaTown_MapScripts::
	.byte 0

FloaromaTown_EventScript_Grunts::
	msgbox FloaromaTown_Text_Grunts, MSGBOX_NPC
	end

FloaromaTown_Text_Grunts:
	.string "GRUNT: Hey! This meadow is\n"
	.string "off-limits! TEAM GALACTIC is busy\l"
	.string "here. Beat it, kid!$"

FloaromaTown_EventScript_PtNpc1::
	msgbox FloaromaTown_Text_PtNpc1, MSGBOX_NPC
	end

FloaromaTown_Text_PtNpc1:
	.string "FLOAROMA was once a barren hill.\n"
	.string "Now it's covered in flowers!$"

FloaromaTown_EventScript_PtNpc2::
	msgbox FloaromaTown_Text_PtNpc2, MSGBOX_NPC
	end

FloaromaTown_Text_PtNpc2:
	.string "The FLOWER SHOP sells things to\n"
	.string "help you grow BERRIES.$"

FloaromaTown_EventScript_PtNpc3::
	msgbox FloaromaTown_Text_PtNpc3, MSGBOX_NPC
	end

FloaromaTown_Text_PtNpc3:
	.string "I love making sweet HONEY with my\n"
	.string "POKéMON!$"

FloaromaTown_EventScript_PtNpc4::
	msgbox FloaromaTown_Text_PtNpc4, MSGBOX_NPC
	end

FloaromaTown_Text_PtNpc4:
	.string "The flowers here are so pretty.\n"
	.string "They say something special made\l"
	.string "them bloom.$"

FloaromaTown_EventScript_PtNpc5::
	msgbox FloaromaTown_Text_PtNpc5, MSGBOX_NPC
	end

FloaromaTown_Text_PtNpc5:
	.string "The meadow north of town is full\n"
	.string "of flowers and HONEY trees.$"

FloaromaTown_EventScript_PtNpc6::
	msgbox FloaromaTown_Text_PtNpc6, MSGBOX_NPC
	end

FloaromaTown_Text_PtNpc6:
	.string "The VALLEY WINDWORKS is east of\n"
	.string "here, past ROUTE 205.$"

FloaromaTown_EventScript_Sign1::
	msgbox FloaromaTown_Text_Sign1, MSGBOX_SIGN
	end

FloaromaTown_Text_Sign1:
	.string "PICK A PECK OF COLORS FLOWER SHOP$"

FloaromaTown_EventScript_Sign2::
	msgbox FloaromaTown_Text_Sign2, MSGBOX_SIGN
	end

FloaromaTown_Text_Sign2:
	.string "FLOAROMA TOWN\p"
	.string "The town of flower scents.$"

FloaromaTown_EventScript_Sign3::
	msgbox FloaromaTown_Text_Sign3, MSGBOX_SIGN
	end

FloaromaTown_Text_Sign3:
	.string "FLOAROMA TOWN\p"
	.string "The town of flower scents.$"

FloaromaTown_EventScript_Sign4::
	msgbox FloaromaTown_Text_Sign4, MSGBOX_SIGN
	end

FloaromaTown_Text_Sign4:
	.string "POKéMON CENTER\p"
	.string "Heal your POKéMON!$"
