OreburghCity_Flat1_F1_MapScripts::
	.byte 0

OreburghCity_Flat1_F1_EventScript_PtNpc1::
	msgbox OreburghCity_Flat1_F1_Text_PtNpc1, MSGBOX_NPC
	end

OreburghCity_Flat1_F1_Text_PtNpc1:
	.string "My POKéMON love the warm air from\n"
	.string "the coal stoves.$"

OreburghCity_Flat1_F1_EventScript_PtNpc2::
	msgbox OreburghCity_Flat1_F1_Text_PtNpc2, MSGBOX_NPC
	end

OreburghCity_Flat1_F1_Text_PtNpc2:
	.string "I'm going to challenge ROARK when\n"
	.string "I'm stronger!$"

OreburghCity_Flat1_F1_EventScript_PtNpc3::
	msgbox OreburghCity_Flat1_F1_Text_PtNpc3, MSGBOX_NPC
	end

OreburghCity_Flat1_F1_Text_PtNpc3:
	.string "The MINING MUSEUM shows how coal\n"
	.string "is dug up. Very interesting!$"
