JubilifeCity_Flat2_F2_MapScripts::
	.byte 0

JubilifeCity_Flat2_F2_EventScript_PtNpc1::
	msgbox JubilifeCity_Flat2_F2_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_Flat2_F2_Text_PtNpc1:
	.string "I'm going to catch my first\n"
	.string "POKéMON on ROUTE 202!$"

JubilifeCity_Flat2_F2_EventScript_PtNpc2::
	msgbox JubilifeCity_Flat2_F2_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_Flat2_F2_Text_PtNpc2:
	.string "My family loves POKéMON. We have\n"
	.string "three at home!$"

JubilifeCity_Flat2_F2_EventScript_PtNpc3::
	msgbox JubilifeCity_Flat2_F2_Text_PtNpc3, MSGBOX_NPC
	end

JubilifeCity_Flat2_F2_Text_PtNpc3:
	.string "I help new Trainers raise healthy\n"
	.string "POKéMON.$"
