OreburghMine_B1F_MapScripts::
	.byte 0

OreburghMine_B1F_EventScript_PtNpc1::
	msgbox OreburghMine_B1F_Text_PtNpc1, MSGBOX_NPC
	end

OreburghMine_B1F_Text_PtNpc1:
	.string "Careful down here! The ground is\n"
	.string "uneven.$"

OreburghMine_B1F_EventScript_PtNpc2::
	msgbox OreburghMine_B1F_Text_PtNpc2, MSGBOX_NPC
	end

OreburghMine_B1F_Text_PtNpc2:
	.string "I'm here on a field trip. The mine\n"
	.string "is so big!$"
