FloaromaTown_House2_MapScripts::
	.byte 0

FloaromaTown_House2_EventScript_PtNpc1::
	msgbox FloaromaTown_House2_Text_PtNpc1, MSGBOX_NPC
	end

FloaromaTown_House2_Text_PtNpc1:
	.string "Our house smells like flowers all\n"
	.string "year round. Isn't that lovely?$"

FloaromaTown_House2_EventScript_PtNpc2::
	msgbox FloaromaTown_House2_Text_PtNpc2, MSGBOX_NPC
	end

FloaromaTown_House2_Text_PtNpc2:
	.string "I came to FLOAROMA to retire. The\n"
	.string "peace and quiet is wonderful.$"
