JubilifeCity_Flat3_F3_MapScripts::
	.byte 0

JubilifeCity_Flat3_F3_EventScript_PtNpc1::
	msgbox JubilifeCity_Flat3_F3_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_Flat3_F3_Text_PtNpc1:
	.string "The top floor is so quiet. I love\n"
	.string "it up here.$"

JubilifeCity_Flat3_F3_EventScript_PtNpc2::
	msgbox JubilifeCity_Flat3_F3_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_Flat3_F3_Text_PtNpc2:
	.string "I collect POKéMON figures. I have\n"
	.string "over a hundred!$"
