OreburghCity_Flat3_F1_MapScripts::
	.byte 0

OreburghCity_Flat3_F1_EventScript_PtNpc1::
	msgbox OreburghCity_Flat3_F1_Text_PtNpc1, MSGBOX_NPC
	end

OreburghCity_Flat3_F1_Text_PtNpc1:
	.string "My family has worked in the mine\n"
	.string "for three generations.$"

OreburghCity_Flat3_F1_EventScript_PtNpc2::
	msgbox OreburghCity_Flat3_F1_Text_PtNpc2, MSGBOX_NPC
	end

OreburghCity_Flat3_F1_Text_PtNpc2:
	.string "I climb mountains on my days off.\n"
	.string "MT. CORONET is my favorite.$"

OreburghCity_Flat3_F1_EventScript_PtNpc3::
	msgbox OreburghCity_Flat3_F1_Text_PtNpc3, MSGBOX_NPC
	end

OreburghCity_Flat3_F1_Text_PtNpc3:
	.string "I trained here for years before\n"
	.string "traveling around Sinnoh.$"
