OreburghCity_House1_MapScripts::
	.byte 0

OreburghCity_House1_EventScript_PtNpc1::
	msgbox OreburghCity_House1_Text_PtNpc1, MSGBOX_NPC
	end

OreburghCity_House1_Text_PtNpc1:
	.string "ROARK'S dad was a GYM LEADER too,\n"
	.string "in a faraway city.$"

OreburghCity_House1_EventScript_PtNpc2::
	msgbox OreburghCity_House1_Text_PtNpc2, MSGBOX_NPC
	end

OreburghCity_House1_Text_PtNpc2:
	.string "The mine never sleeps. Somebody is\n"
	.string "always working down there.$"
