EternaCity_UndergroundManHouse_MapScripts::
	.byte 0

EternaCity_UndergroundManHouse_EventScript_PtNpc1::
	msgbox EternaCity_UndergroundManHouse_Text_PtNpc1, MSGBOX_NPC
	end

EternaCity_UndergroundManHouse_Text_PtNpc1:
	.string "My grandpa is the UNDERGROUND MAN!\n"
	.string "He's dug tunnels all over Sinnoh.$"

EternaCity_UndergroundManHouse_EventScript_PtNpc2::
	msgbox EternaCity_UndergroundManHouse_Text_PtNpc2, MSGBOX_NPC
	end

EternaCity_UndergroundManHouse_Text_PtNpc2:
	.string "We study the fossils found\n"
	.string "underground.$"

EternaCity_UndergroundManHouse_EventScript_PtNpc3::
	msgbox EternaCity_UndergroundManHouse_Text_PtNpc3, MSGBOX_NPC
	end

EternaCity_UndergroundManHouse_Text_PtNpc3:
	.string "The UNDERGROUND is full of\n"
	.string "treasure, if you know where to\l"
	.string "dig.$"

EternaCity_UndergroundManHouse_EventScript_PtNpc4::
	msgbox EternaCity_UndergroundManHouse_Text_PtNpc4, MSGBOX_NPC
	end

EternaCity_UndergroundManHouse_Text_PtNpc4:
	.string "I found a shiny sphere once! It\n"
	.string "was beautiful.$"

EternaCity_UndergroundManHouse_EventScript_UndergroundMan::
	msgbox EternaCity_UndergroundManHouse_Text_Man, MSGBOX_NPC
	end

EternaCity_UndergroundManHouse_Text_Man:
	.string "UNDERGROUND MAN: Hohoh! I've dug\n"
	.string "tunnels under all of Sinnoh!\p"
	.string "The UNDERGROUND is closed to\n"
	.string "visitors for now, but come back\l"
	.string "someday. There are treasures down\n"
	.string "there!$"
