JubilifeCity_JubilifeTV_F4_MapScripts::
	.byte 0

JubilifeCity_JubilifeTV_F4_EventScript_PtNpc1::
	msgbox JubilifeCity_JubilifeTV_F4_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F4_Text_PtNpc1:
	.string "From up here, you can see the\n"
	.string "whole of JUBILIFE. Isn't it\l"
	.string "wonderful?$"

JubilifeCity_JubilifeTV_F4_EventScript_PtNpc2::
	msgbox JubilifeCity_JubilifeTV_F4_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F4_Text_PtNpc2:
	.string "This is the director's floor.\n"
	.string "Please don't touch the equipment!$"

JubilifeCity_JubilifeTV_F4_EventScript_PtNpc3::
	msgbox JubilifeCity_JubilifeTV_F4_Text_PtNpc3, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F4_Text_PtNpc3:
	.string "My POKéMON appeared on TV once. It\n"
	.string "was so nervous!$"
