EternaCity_Flat1_F2_MapScripts::
	.byte 0

EternaCity_Flat1_F2_EventScript_PtNpc1::
	msgbox EternaCity_Flat1_F2_Text_PtNpc1, MSGBOX_NPC
	end

EternaCity_Flat1_F2_Text_PtNpc1:
	.string "My grandmother knows all the old\n"
	.string "legends of Sinnoh.$"

EternaCity_Flat1_F2_EventScript_PtNpc2::
	msgbox EternaCity_Flat1_F2_Text_PtNpc2, MSGBOX_NPC
	end

EternaCity_Flat1_F2_Text_PtNpc2:
	.string "I love this building. It has such\n"
	.string "a nice view of the statue!$"

EternaCity_Flat1_F2_EventScript_PtNpc3::
	msgbox EternaCity_Flat1_F2_Text_PtNpc3, MSGBOX_NPC
	end

EternaCity_Flat1_F2_Text_PtNpc3:
	.string "The stories say three POKéMON live\n"
	.string "in the lakes of Sinnoh.$"
