JubilifeCity_Flat1_F2_MapScripts::
	.byte 0

JubilifeCity_Flat1_F2_EventScript_PtNpc1::
	msgbox JubilifeCity_Flat1_F2_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_Flat1_F2_Text_PtNpc1:
	.string "I'm training to beat the OREBURGH\n"
	.string "GYM. ROCK-types are tough!$"

JubilifeCity_Flat1_F2_EventScript_PtNpc2::
	msgbox JubilifeCity_Flat1_F2_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_Flat1_F2_Text_PtNpc2:
	.string "I love dressing up my POKéMON for\n"
	.string "contests.$"

JubilifeCity_Flat1_F2_EventScript_PtNpc3::
	msgbox JubilifeCity_Flat1_F2_Text_PtNpc3, MSGBOX_NPC
	end

JubilifeCity_Flat1_F2_Text_PtNpc3:
	.string "I collect rare stones. OREBURGH is\n"
	.string "the best place to find them!$"

JubilifeCity_Flat1_F2_EventScript_PtNpc4::
	msgbox JubilifeCity_Flat1_F2_Text_PtNpc4, MSGBOX_NPC
	end

JubilifeCity_Flat1_F2_Text_PtNpc4:
	.string "Have you seen the TRAINERS'\n"
	.string "SCHOOL? It's right in the middle\l"
	.string "of town!$"
