OreburghCity_Flat1_F2_MapScripts::
	.byte 0

OreburghCity_Flat1_F2_EventScript_PtNpc1::
	msgbox OreburghCity_Flat1_F2_Text_PtNpc1, MSGBOX_NPC
	end

OreburghCity_Flat1_F2_Text_PtNpc1:
	.string "Night shift again. I'd better get\n"
	.string "some sleep.$"

OreburghCity_Flat1_F2_EventScript_PtNpc2::
	msgbox OreburghCity_Flat1_F2_Text_PtNpc2, MSGBOX_NPC
	end

OreburghCity_Flat1_F2_Text_PtNpc2:
	.string "I found a fossil in the mine\n"
	.string "yesterday! I think...$"

OreburghCity_Flat1_F2_EventScript_PtNpc3::
	msgbox OreburghCity_Flat1_F2_Text_PtNpc3, MSGBOX_NPC
	end

OreburghCity_Flat1_F2_Text_PtNpc3:
	.string "I want to be a miner like my dad!$"

OreburghCity_Flat1_F2_EventScript_PtNpc4::
	msgbox OreburghCity_Flat1_F2_Text_PtNpc4, MSGBOX_NPC
	end

OreburghCity_Flat1_F2_Text_PtNpc4:
	.string "Psyduck... Psy?$"
