JubilifeCity_JubilifeTV_F2_MapScripts::
	.byte 0

JubilifeCity_JubilifeTV_F2_EventScript_PtNpc1::
	msgbox JubilifeCity_JubilifeTV_F2_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F2_Text_PtNpc1:
	.string "La la la! I'm practicing for my\n"
	.string "big performance today!$"

JubilifeCity_JubilifeTV_F2_EventScript_PtNpc2::
	msgbox JubilifeCity_JubilifeTV_F2_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F2_Text_PtNpc2:
	.string "This floor is for programs about\n"
	.string "POKéMON. Very popular!$"

JubilifeCity_JubilifeTV_F2_EventScript_PtNpc3::
	msgbox JubilifeCity_JubilifeTV_F2_Text_PtNpc3, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F2_Text_PtNpc3:
	.string "Hey! I'm the security guard.\n"
	.string "Behave yourself, all right?$"
