JubilifeCity_Flat1_F1_MapScripts::
	.byte 0

JubilifeCity_Flat1_F1_EventScript_PtNpc1::
	msgbox JubilifeCity_Flat1_F1_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_Flat1_F1_Text_PtNpc1:
	.string "I'm waiting for my friend to come\n"
	.string "over and trade.$"

JubilifeCity_Flat1_F1_EventScript_PtNpc2::
	msgbox JubilifeCity_Flat1_F1_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_Flat1_F1_Text_PtNpc2:
	.string "Pika!$"

JubilifeCity_Flat1_F1_EventScript_PtNpc3::
	msgbox JubilifeCity_Flat1_F1_Text_PtNpc3, MSGBOX_NPC
	end

JubilifeCity_Flat1_F1_Text_PtNpc3:
	.string "I work at the TV station. Long\n"
	.string "hours, but it's fun!$"
