EternaCity_Flat1_F3_MapScripts::
	.byte 0

EternaCity_Flat1_F3_EventScript_PtNpc1::
	msgbox EternaCity_Flat1_F3_Text_PtNpc1, MSGBOX_NPC
	end

EternaCity_Flat1_F3_Text_PtNpc1:
	.string "From the top floor you can see all\n"
	.string "of ETERNA.$"

EternaCity_Flat1_F3_EventScript_PtNpc2::
	msgbox EternaCity_Flat1_F3_Text_PtNpc2, MSGBOX_NPC
	end

EternaCity_Flat1_F3_Text_PtNpc2:
	.string "I'm studying hard to become a\n"
	.string "great Trainer!$"

EternaCity_Flat1_F3_EventScript_PtNpc3::
	msgbox EternaCity_Flat1_F3_Text_PtNpc3, MSGBOX_NPC
	end

EternaCity_Flat1_F3_Text_PtNpc3:
	.string "The forest is full of BUG POKéMON.\n"
	.string "I love it!$"

EternaCity_Flat1_F3_EventScript_PtNpc4::
	msgbox EternaCity_Flat1_F3_Text_PtNpc4, MSGBOX_NPC
	end

EternaCity_Flat1_F3_Text_PtNpc4:
	.string "Shh! I'm practicing being\n"
	.string "invisible!$"
