EternaCity_Flat1_F1_MapScripts::
	.byte 0

EternaCity_Flat1_F1_EventScript_PtNpc1::
	msgbox EternaCity_Flat1_F1_Text_PtNpc1, MSGBOX_NPC
	end

EternaCity_Flat1_F1_Text_PtNpc1:
	.string "I train my body and mind every\n"
	.string "day, just like a ninja!$"

EternaCity_Flat1_F1_EventScript_PtNpc2::
	msgbox EternaCity_Flat1_F1_Text_PtNpc2, MSGBOX_NPC
	end

EternaCity_Flat1_F1_Text_PtNpc2:
	.string "This building has been here for a\n"
	.string "very long time.$"

EternaCity_Flat1_F1_EventScript_PtNpc3::
	msgbox EternaCity_Flat1_F1_Text_PtNpc3, MSGBOX_NPC
	end

EternaCity_Flat1_F1_Text_PtNpc3:
	.string "Nicknames show how much you care\n"
	.string "about your POKéMON.$"
