OreburghCity_Flat2_F2_MapScripts::
	.byte 0

OreburghCity_Flat2_F2_EventScript_PtNpc1::
	msgbox OreburghCity_Flat2_F2_Text_PtNpc1, MSGBOX_NPC
	end

OreburghCity_Flat2_F2_Text_PtNpc1:
	.string "I'm writing a song called COAL\n"
	.string "HEART. What do you think?$"

OreburghCity_Flat2_F2_EventScript_PtNpc2::
	msgbox OreburghCity_Flat2_F2_Text_PtNpc2, MSGBOX_NPC
	end

OreburghCity_Flat2_F2_Text_PtNpc2:
	.string "I raise GEODUDE. They're heavier\n"
	.string "than they look!$"

OreburghCity_Flat2_F2_EventScript_PtNpc3::
	msgbox OreburghCity_Flat2_F2_Text_PtNpc3, MSGBOX_NPC
	end

OreburghCity_Flat2_F2_Text_PtNpc3:
	.string "I collect fossils. Some are older\n"
	.string "than Sinnoh itself!$"
