JubilifeCity_JubilifeTV_F3_MapScripts::
	.byte 0

JubilifeCity_JubilifeTV_F3_EventScript_PtNpc1::
	msgbox JubilifeCity_JubilifeTV_F3_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_Text_PtNpc1:
	.string "The camera loves me! Wait... is it\n"
	.string "even on?$"

JubilifeCity_JubilifeTV_F3_EventScript_PtNpc2::
	msgbox JubilifeCity_JubilifeTV_F3_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_Text_PtNpc2:
	.string "We're filming a show about the\n"
	.string "most beautiful POKéMON.$"

JubilifeCity_JubilifeTV_F3_EventScript_PtNpc3::
	msgbox JubilifeCity_JubilifeTV_F3_Text_PtNpc3, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_Text_PtNpc3:
	.string "Quiet on the set, please! We're\n"
	.string "about to start recording.$"

JubilifeCity_JubilifeTV_F3_EventScript_PtNpc4::
	msgbox JubilifeCity_JubilifeTV_F3_Text_PtNpc4, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F3_Text_PtNpc4:
	.string "I edit the footage. It takes hours\n"
	.string "to make a short program!$"
