JubilifeCity_JubilifeTV_F1_MapScripts::
	.byte 0

JubilifeCity_JubilifeTV_F1_EventScript_PtNpc1::
	msgbox JubilifeCity_JubilifeTV_F1_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F1_Text_PtNpc1:
	.string "Welcome to JUBILIFE TV! Feel free\n"
	.string "to look around.$"

JubilifeCity_JubilifeTV_F1_EventScript_PtNpc2::
	msgbox JubilifeCity_JubilifeTV_F1_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F1_Text_PtNpc2:
	.string "I'm here to see how TV shows are\n"
	.string "made!$"

JubilifeCity_JubilifeTV_F1_EventScript_PtNpc3::
	msgbox JubilifeCity_JubilifeTV_F1_Text_PtNpc3, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F1_Text_PtNpc3:
	.string "I came all the way here to be on\n"
	.string "TV. Do I look ready?$"

JubilifeCity_JubilifeTV_F1_EventScript_PtNpc4::
	msgbox JubilifeCity_JubilifeTV_F1_Text_PtNpc4, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F1_Text_PtNpc4:
	.string "It's cold outside, but the studios\n"
	.string "here are nice and warm.$"

JubilifeCity_JubilifeTV_F1_EventScript_PtNpc5::
	msgbox JubilifeCity_JubilifeTV_F1_Text_PtNpc5, MSGBOX_NPC
	end

JubilifeCity_JubilifeTV_F1_Text_PtNpc5:
	.string "I heard a famous Trainer is being\n"
	.string "interviewed today!$"
