OreburghCity_House2_MapScripts::
	.byte 0

OreburghCity_House2_EventScript_PtNpc1::
	msgbox OreburghCity_House2_Text_PtNpc1, MSGBOX_NPC
	end

OreburghCity_House2_Text_PtNpc1:
	.string "I want to catch a GEODUDE in\n"
	.string "OREBURGH GATE.$"

OreburghCity_House2_EventScript_PtNpc2::
	msgbox OreburghCity_House2_Text_PtNpc2, MSGBOX_NPC
	end

OreburghCity_House2_Text_PtNpc2:
	.string "My son spends all day at the GYM\n"
	.string "watching battles.$"

OreburghCity_House2_EventScript_PtNpc3::
	msgbox OreburghCity_House2_Text_PtNpc3, MSGBOX_NPC
	end

OreburghCity_House2_Text_PtNpc3:
	.string "Pika!$"
