JubilifeCity_Flat3_F1_MapScripts::
	.byte 0

JubilifeCity_Flat3_F1_EventScript_PtNpc1::
	msgbox JubilifeCity_Flat3_F1_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_Flat3_F1_Text_PtNpc1:
	.string "These condominiums are the nicest\n"
	.string "in JUBILIFE.$"

JubilifeCity_Flat3_F1_EventScript_PtNpc2::
	msgbox JubilifeCity_Flat3_F1_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_Flat3_F1_Text_PtNpc2:
	.string "Pachi-pachi!$"

JubilifeCity_Flat3_F1_EventScript_PtNpc3::
	msgbox JubilifeCity_Flat3_F1_Text_PtNpc3, MSGBOX_NPC
	end

JubilifeCity_Flat3_F1_Text_PtNpc3:
	.string "Pika pika!$"

JubilifeCity_Flat3_F1_EventScript_PtNpc4::
	msgbox JubilifeCity_Flat3_F1_Text_PtNpc4, MSGBOX_NPC
	end

JubilifeCity_Flat3_F1_Text_PtNpc4:
	.string "I moved here for the view of the\n"
	.string "city lights at night.$"
