Route205_House_MapScripts::
	.byte 0

Route205_House_EventScript_PtNpc1::
	msgbox Route205_House_Text_PtNpc1, MSGBOX_NPC
	end

Route205_House_Text_PtNpc1:
	.string "Welcome, traveler! Rest here\n"
	.string "before crossing ETERNA FOREST.$"

Route205_House_EventScript_PtNpc2::
	msgbox Route205_House_Text_PtNpc2, MSGBOX_NPC
	end

Route205_House_Text_PtNpc2:
	.string "The forest is dark and easy to get\n"
	.string "lost in. Stick to the path!$"
