TwinleafTown_House2_MapScripts::
	.byte 0

TwinleafTown_House2_EventScript_OldMan::
	msgbox TwinleafTown_House2_Text_OldMan, MSGBOX_NPC
	end

TwinleafTown_House2_EventScript_OldWoman::
	msgbox TwinleafTown_House2_Text_OldWoman, MSGBOX_NPC
	end

TwinleafTown_House2_Text_OldMan:
	.string "TWINLEAF has changed little in\n"
	.string "fifty years. That's what I love\l"
	.string "about it.$"

TwinleafTown_House2_Text_OldWoman:
	.string "The lake to the west is said to be\n"
	.string "home to a POKéMON of great wisdom.$"

