Twinleaf_Town_RivalsHouse_F1_MapScripts::
	.byte 0

Twinleaf_Town_RivalsHouse_F1_EventScript_PtNpc1::
	msgbox Twinleaf_Town_RivalsHouse_F1_Text_PtNpc1, MSGBOX_NPC
	end

Twinleaf_Town_RivalsHouse_F1_Text_PtNpc1:
	.string "Barry's always in a hurry. He even\n"
	.string "eats breakfast running out the\l"
	.string "door!\p"
	.string "His father is a very strong\n"
	.string "Trainer, you know. Barry wants to\l"
	.string "be just like him.$"
