Twinleaf_Town_RivalsHouse_F1_MapScripts::
	.byte 0

Twinleaf_Town_RivalsHouse_F1_EventScript_BarrysMom::
	msgbox Twinleaf_Town_RivalsHouse_F1_Text_BarrysMom, MSGBOX_NPC
	end

Twinleaf_Town_RivalsHouse_F1_Text_BarrysMom:
	.string "Oh, {PLAYER}! Barry left in such a\n"
	.string "rush. That boy is always running\l"
	.string "somewhere!\p"
	.string "If you see him, tell him to slow\n"
	.string "down once in a while.$"

