JubilifeCity_PoketchCompany_F2_MapScripts::
	.byte 0

JubilifeCity_PoketchCompany_F2_EventScript_PtNpc1::
	msgbox JubilifeCity_PoketchCompany_F2_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_Text_PtNpc1:
	.string "The POKéTCH was invented to make\n"
	.string "Trainers' lives easier.$"

JubilifeCity_PoketchCompany_F2_EventScript_PtNpc2::
	msgbox JubilifeCity_PoketchCompany_F2_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_Text_PtNpc2:
	.string "In my day, we didn't have fancy\n"
	.string "watches! We just used the sun.$"

JubilifeCity_PoketchCompany_F2_EventScript_PtNpc3::
	msgbox JubilifeCity_PoketchCompany_F2_Text_PtNpc3, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_Text_PtNpc3:
	.string "Clefairy! Fairy fairy!$"

JubilifeCity_PoketchCompany_F2_EventScript_PtNpc4::
	msgbox JubilifeCity_PoketchCompany_F2_Text_PtNpc4, MSGBOX_NPC
	end

JubilifeCity_PoketchCompany_F2_Text_PtNpc4:
	.string "Pachi-pachi! It's running around\n"
	.string "the office!$"
