JubilifeCity_Flat3_F2_MapScripts::
	.byte 0

JubilifeCity_Flat3_F2_EventScript_PtNpc1::
	msgbox JubilifeCity_Flat3_F2_Text_PtNpc1, MSGBOX_NPC
	end

JubilifeCity_Flat3_F2_Text_PtNpc1:
	.string "I found a BURMY in the park! Its\n"
	.string "cloak is made of leaves!$"

JubilifeCity_Flat3_F2_EventScript_PtNpc2::
	msgbox JubilifeCity_Flat3_F2_Text_PtNpc2, MSGBOX_NPC
	end

JubilifeCity_Flat3_F2_Text_PtNpc2:
	.string "I'm raising POKéMON in my\n"
	.string "apartment. It's a bit crowded!$"
